server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      enabled: true
      force: true
      charset: utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wwp.pojo

